### ISSUE TITLE
Error 404 in Flatpak

### ISSUE THREAD

**Issue by cunidev** [stanford-oval/almond-gnome#57]
Seems like the Flatpak is broken for some reason, as it can't send any command to the server. I enabled Passive Training, if that counts.

![image](https://user-images.githubusercontent.com/13885615/70895133-a8081180-1fee-11ea-9489-dfd34fe1ecbf.png)

**Comment by gcampax** [comment]
Mh that's not expected. May I ask what locale you are running under?

**Comment by cunidev** [comment]
de_DE I think. It was something like almond-nl.stanford.edu, does it exist?

**Comment by gcampax** [comment]
I think the problem is that it tries to ask the server for the German model, because of your locale. That model doesn't exist, and you get an error. We should probably limit the choice of language to the supported ones only.

**Comment by cunidev** [comment]
The endpoint is hardcoded to `https://almond-nl.stanford.edu/`. Running `LC_ALL=C LANG=C flatpak run edu.stanford.Almond` does not solve the issue

**Comment by gcampax** [comment]
The endpoint is correct (NL is short for "natural language", it's not the Netherlands country code). Try `LC_ALL=en_US flatpak run edu.stanford.Almond` and it might help. `C` is not a recognized language either, because posix locales are not quite the same as language tags.

**Comment by cunidev** [comment]
I still get that 404 for some reason...

**Comment by cunidev** [comment]
The web demo seems to point requests to almond.stanford.edu rather than almond-nl.stanford.edu?

**Comment by gcampax** [comment]
The web demo uses a websocket connection to a server running at almond.stanford.edu. That server then issues REST calls to almond-nl.stanford.edu.
The complete endpoint would be something like https://almond-nl.stanford.edu/en-US/query?q=what%20time%20is%20it

Anyway, would you be able to test that PR and see if it helps?

**Comment by cunidev** [comment]
Sure, I'll compile the code and test it later. Is the TTS engine needed for compilation?

**Comment by gcampax** [comment]
It depends how you compile it. If you build the flatpak, it will build all the dependencies (which will take a while). If you run locally, you will need mimic (TTS) but you will be able to skip the hotword detection code. To build locally, use `yarn` to build the service, and `node ./service/main.js` to start the service; use `meson build` to build the gtk frontend, and `./src/edu.stanford.Almond` to start it.
