### ISSUE TITLE
Create a true dark theme

### ISSUE THREAD

**Issue by airon90** [stanford-oval/almond-gnome#73]
I'm using Almond on latest GNOME (3.36 as of now) with Materia dark theme. I cannot see what the program writes in the window

![Schermata da 2020-06-16 17-02-50](https://user-images.githubusercontent.com/139841/84791680-3d627d80-aff3-11ea-9916-c83e52f57e50.png)

**Comment by gcampax** [comment]
Hi, thanks for your report! At the moment, we only support the Adwaita theme, and only in the light variant. Other themes will have issues, as you noticed.
If you would like your theme to be supported, you or the theme developers will have to provide a PR with the appropriate style.

**Comment by aurium** [comment]
Hi @gcampax, i try to find "Adwaita" string inside this project, but i found noting. So, I believe the theme compatibility is hardcoded. Am i right? I'm interested to solve the dark theme problem, but i know nothing about the project. Can you point me what i must to look for and whet to do? Thanks!

**Comment by gcampax** [comment]
Adwaita is the default Gtk theme, so the name will not be present in our source code (Adwaita-dark is the dark version).
Our custom CSS is in data/application.css. I know there is a way to load different CSS for light and dark themes, but I don't quite remember what it is, so I suggest you look for that first.

**Comment by aurium** [comment]
@gcampax what about make this change to `data/application.css`?

```css
.message {
  color: @fg_color; /* or text-decoration-color? */
  background-color: @bg_color;
  background-clip: content-box;
}
```
I believe this variables are defined based on this document:
https://github.com/surajmandalcell/Gtk-Theming-Guide/blob/master/creating_gtk_themes.md

However, nothing changes when I ran:
`sudo flatpak-builder --install --force-clean --install-deps-from=flathub _app edu.stanford.Almond.json`

I also try `background-color: red` to be sure, and I see no change.

**Comment by gcampax** [comment]
How are you building and testing Almond? The best way is through GNOME Builder, which will rebuild and make sure you're running the right version you just built, rather than the installed version or any version from a repo.

**Comment by aurium** [comment]
@gcampax, I did try to use GBuilder (it is nice), but it does not enable the run button. It compiles (the log is ok), but `Ctrl+F5` does nothing.

You can see my [compilation log](https://github.com/stanford-oval/almond-gnome/files/6046589/almond-compilation.log).

**Comment by gcampax** [comment]
Can I see the run log? The "Run" button works for me on GNOME Builder installed from Flatpak, opening almond-gnome from the git repository.

**Comment by aurium** [comment]
There is no "run log" because the run button is disabled. I did install the Gnome Builder from APT. The almond-gnome is a clone from this git repository. I'm installing GBuilder from flatpak now to see if it works.

**Comment by aurium** [comment]
@gcampax the run button is enabled on GBuilder from Flatpak, however, the build fails. (and i don't know this building process)

[almond-compilation-FAIL.log](https://github.com/stanford-oval/almond-gnome/files/6046879/almond-compilation-FAIL.log)

**Comment by gcampax** [comment]
To fix that particular build problem, run `./travis/download-deps.py` from a terminal from inside the almond-gnome git repository. It will download the dependencies and allow the build to run without network access.

**Comment by aurium** [comment]
Finally works!
Now i can see the CSS changes take effect.

Thank you @gcampax! Tomorrow I'll work on this.
