### ISSUE TITLE
Flatpak install require org.gnome.Platform 3.34

### ISSUE THREAD

**Issue by maymage** [stanford-oval/almond-gnome#93]
Hi, 

I just wanted to install Almond on Ubuntu 20.04. Strangely the flatpak install requires `org.gnome.Platform 3.34`, 
while `org.gnome.Platform 3.36` is available and the runtime has already [switched](https://github.com/stanford-oval/almond-gnome/pull/65) to the latter version..  Nice screenshot below

![Flatpak_Install](https://user-images.githubusercontent.com/36572014/92321301-18e1d480-f029-11ea-8fed-5ccbe5461f0b.png)

**Comment by gcampax** [comment]
Hi @maymage, thanks for your report!

Multiple flatpak runtimes for the same ID can be installed in parallel, so it is not a problem that we use 3.34. Identical files (icons, translations, etc.) are automatically deduplicated between the two runtimes.

Additionally, you're looking to install the stable version of Almond (1.8), which was released in [early April](https://wiki.almond.stanford.edu/release-planning/one-point-eight) before the 3.36 runtime was stable.
The next version of Almond uses the 3.36 runtime, but not that the next version is a development version in preparation for Almond 2.0, and will not be released on Flathub. You will need to try it from the [nightly build server](https://flatpak.almond.stanford.edu/) if you're interested in testing it.
You can learn more about our release plan in our [wiki](https://wiki.almond.stanford.edu/release-planning/one-point-eight).
